# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-10 07:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassInfo',
            fields=[
                ('cls_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('cls_name', models.CharField(max_length=20)),
                ('master_name', models.CharField(max_length=20)),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'classes',
            },
        ),
        migrations.CreateModel(
            name='DepartmentInfo',
            fields=[
                ('dep_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dep_name', models.CharField(max_length=20)),
                ('master_name', models.CharField(max_length=20)),
                ('slogan', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('stu_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('stu_name', models.CharField(max_length=20)),
                ('gender', models.BooleanField(default=True)),
                ('birthday', models.DateField()),
                ('native', models.CharField(max_length=20)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=8, null=True)),
                ('email', models.CharField(blank=True, max_length=20, null=True)),
                ('note', models.CharField(blank=True, max_length=200, null=True)),
                ('cls', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.ClassInfo')),
                ('dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DepartmentInfo')),
            ],
            options={
                'db_table': 'students',
            },
        ),
        migrations.AddField(
            model_name='classinfo',
            name='dep',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.DepartmentInfo'),
        ),
    ]
